"""Curated national-security gazetteer for high-precision entity matching.

Maps a lowercase surface form to a (canonical name, entity type) pair.
Entity types: place, organization, person, group, product, concept.

Entries are added when a corpus-wide review (see ailandscape/review.py and
the `review` CLI) shows a surface form appearing in many documents without
being canonicalized. Highest priority: defense industry, US government /
military, major AI / tech companies, sitting heads of state and senior
officials, and AI capabilities.
"""

GAZETTEER = {
    # --- countries / places ---
    "united states": ("United States", "place"),
    "u.s.": ("United States", "place"),
    "america": ("United States", "place"),
    "china": ("China", "place"),
    "russia": ("Russia", "place"),
    "ukraine": ("Ukraine", "place"),
    "iran": ("Iran", "place"),
    "north korea": ("North Korea", "place"),
    "south korea": ("South Korea", "place"),
    "israel": ("Israel", "place"),
    "taiwan": ("Taiwan", "place"),
    "india": ("India", "place"),
    "japan": ("Japan", "place"),
    "united kingdom": ("United Kingdom", "place"),
    "u.k.": ("United Kingdom", "place"),
    "germany": ("Germany", "place"),
    "france": ("France", "place"),
    "australia": ("Australia", "place"),
    "pacific": ("Pacific", "place"),
    "indo-pacific": ("Indo-Pacific", "place"),
    "middle east": ("Middle East", "place"),
    "europe": ("Europe", "place"),
    "poland": ("Poland", "place"),
    "sweden": ("Sweden", "place"),
    "finland": ("Finland", "place"),
    "norway": ("Norway", "place"),
    "denmark": ("Denmark", "place"),
    "netherlands": ("Netherlands", "place"),
    "belgium": ("Belgium", "place"),
    "italy": ("Italy", "place"),
    "spain": ("Spain", "place"),
    "greece": ("Greece", "place"),
    "turkey": ("Turkey", "place"),
    "romania": ("Romania", "place"),
    "canada": ("Canada", "place"),
    "mexico": ("Mexico", "place"),
    "cuba": ("Cuba", "place"),
    "venezuela": ("Venezuela", "place"),
    "egypt": ("Egypt", "place"),
    "saudi arabia": ("Saudi Arabia", "place"),
    "united arab emirates": ("United Arab Emirates", "place"),
    "qatar": ("Qatar", "place"),
    "iraq": ("Iraq", "place"),
    "syria": ("Syria", "place"),
    "yemen": ("Yemen", "place"),
    "afghanistan": ("Afghanistan", "place"),
    "pakistan": ("Pakistan", "place"),
    "vietnam": ("Vietnam", "place"),
    "philippines": ("Philippines", "place"),
    "singapore": ("Singapore", "place"),
    "argentina": ("Argentina", "place"),
    "strait of hormuz": ("Strait of Hormuz", "place"),
    # --- organizations / agencies ---
    "pentagon": ("Pentagon", "organization"),
    "department of defense": ("Department of Defense", "organization"),
    "dod": ("Department of Defense", "organization"),
    "u.s. military": ("U.S. Military", "organization"),
    "white house": ("White House", "organization"),
    "congress": ("Congress", "organization"),
    "navy": ("U.S. Navy", "organization"),
    "u.s. navy": ("U.S. Navy", "organization"),
    "army": ("U.S. Army", "organization"),
    "u.s. army": ("U.S. Army", "organization"),
    "air force": ("U.S. Air Force", "organization"),
    "space force": ("U.S. Space Force", "organization"),
    "marine corps": ("U.S. Marine Corps", "organization"),
    "cia": ("Central Intelligence Agency", "organization"),
    "nsa": ("National Security Agency", "organization"),
    "fbi": ("Federal Bureau of Investigation", "organization"),
    "darpa": ("DARPA", "organization"),
    "nato": ("NATO", "organization"),
    "united nations": ("United Nations", "organization"),
    "european union": ("European Union", "organization"),
    "pla": ("People's Liberation Army", "organization"),
    "people's liberation army": ("People's Liberation Army", "organization"),
    "socom": ("U.S. Special Operations Command", "organization"),
    "ussocom": ("U.S. Special Operations Command", "organization"),
    "centcom": ("U.S. Central Command", "organization"),
    "southcom": ("U.S. Southern Command", "organization"),
    "afsoc": ("U.S. Air Force Special Operations Command", "organization"),
    "coast guard": ("U.S. Coast Guard", "organization"),
    "national guard": ("National Guard", "organization"),
    "irgc": ("Islamic Revolutionary Guard Corps", "organization"),
    "eu": ("European Union", "organization"),
    "un": ("United Nations", "organization"),
    "nato": ("NATO", "organization"),
    "norad": ("NORAD", "organization"),
    "north atlantic treaty organization": ("NATO", "organization"),
    "library of congress": ("Library of Congress", "organization"),
    "congressional research service": ("Congressional Research Service",
                                          "organization"),
    "crs": ("Congressional Research Service", "organization"),
    "office of the director of national intelligence":
        ("Office of the Director of National Intelligence", "organization"),
    "odni": ("Office of the Director of National Intelligence",
              "organization"),
    # --- major tech / AI companies ---
    "google": ("Google", "organization"),
    "microsoft": ("Microsoft", "organization"),
    "apple": ("Apple", "organization"),
    "amazon": ("Amazon", "organization"),
    "meta": ("Meta", "organization"),
    "nvidia": ("NVIDIA", "organization"),
    "google deepmind": ("Google DeepMind", "organization"),
    "deepmind": ("Google DeepMind", "organization"),
    "anthropic": ("Anthropic", "organization"),
    "cisco": ("Cisco", "organization"),
    "general electric": ("General Electric", "organization"),
    "sukhoi": ("Sukhoi", "organization"),
    "mbda": ("MBDA", "organization"),
    "av": ("AeroVironment", "organization"),
    # --- defense industry ---
    "lockheed martin": ("Lockheed Martin", "organization"),
    "boeing": ("Boeing", "organization"),
    "raytheon": ("Raytheon", "organization"),
    "rtx": ("RTX", "organization"),
    "northrop grumman": ("Northrop Grumman", "organization"),
    "general dynamics": ("General Dynamics", "organization"),
    "general atomics": ("General Atomics", "organization"),
    "bae systems": ("BAE Systems", "organization"),
    "l3harris": ("L3Harris", "organization"),
    "anduril": ("Anduril", "organization"),
    "palantir": ("Palantir", "organization"),
    "spacex": ("SpaceX", "organization"),
    "openai": ("OpenAI", "organization"),
    "shield ai": ("Shield AI", "organization"),
    "teledyne flir": ("Teledyne FLIR", "organization"),
    "aerovironment": ("AeroVironment", "organization"),
    "bluehalo": ("BlueHalo", "organization"),
    "saildrone": ("Saildrone", "organization"),
    "israel aerospace industries": ("Israel Aerospace Industries", "organization"),
    "iai": ("Israel Aerospace Industries", "organization"),
    "reveal technology": ("Reveal Technology", "organization"),
    "dfl technology": ("DFL Technology", "organization"),
    "sofwerx": ("SOFWERX", "organization"),
    "defense autonomous warfare group": (
        "Defense Autonomous Warfare Group", "organization"
    ),
    "dawg": ("Defense Autonomous Warfare Group", "organization"),
    "defense innovation unit": ("Defense Innovation Unit", "organization"),
    # --- products / systems ---
    "f-35": ("F-35", "product"),
    "f-16": ("F-16", "product"),
    "b-21": ("B-21 Raider", "product"),
    "patriot": ("Patriot missile system", "product"),
    "pac-3": ("PAC-3", "product"),
    "tomahawk": ("Tomahawk missile", "product"),
    "himars": ("HIMARS", "product"),
    "thaad": ("THAAD", "product"),
    "next generation interceptor": ("Next Generation Interceptor", "product"),
    "precision strike missile": ("Precision Strike Missile", "product"),
    "prsm": ("Precision Strike Missile", "product"),
    "reaper": ("MQ-9 Reaper", "product"),
    "mq-9": ("MQ-9 Reaper", "product"),
    "global hawk": ("Global Hawk", "product"),
    "switchblade": ("Switchblade", "product"),
    "harop": ("Harop", "product"),
    "yfq-42a": ("YFQ-42A", "product"),
    "yfq-44a": ("YFQ-44A", "product"),
    "uh-1y venom": ("UH-1Y Venom", "product"),
    "ah-1z viper": ("AH-1Z Viper", "product"),
    "identifi": ("Identifi", "product"),
    "bradley fighting vehicle": ("Bradley Fighting Vehicle", "product"),
    "ah-64 apache": ("AH-64 Apache", "product"),
    "f-15e": ("F-15E Strike Eagle", "product"),
    "f-15e strike eagle": ("F-15E Strike Eagle", "product"),
    "kc-135 stratotanker": ("KC-135 Stratotanker", "product"),
    "f/a-18": ("F/A-18 Hornet", "product"),
    "mq-1": ("MQ-1 Predator", "product"),
    "spear 3": ("SPEAR 3", "product"),
    # --- major political figures (named ~daily in this corpus) ---
    "donald trump": ("Donald Trump", "person"),
    "trump": ("Donald Trump", "person"),
    "joe biden": ("Joe Biden", "person"),
    "biden": ("Joe Biden", "person"),
    "vladimir putin": ("Vladimir Putin", "person"),
    "putin": ("Vladimir Putin", "person"),
    "xi jinping": ("Xi Jinping", "person"),
    "volodymyr zelenskyy": ("Volodymyr Zelenskyy", "person"),
    "zelenskyy": ("Volodymyr Zelenskyy", "person"),
    "marco rubio": ("Marco Rubio", "person"),
    "rubio": ("Marco Rubio", "person"),
    "pete hegseth": ("Pete Hegseth", "person"),
    "hegseth": ("Pete Hegseth", "person"),
    "benjamin netanyahu": ("Benjamin Netanyahu", "person"),
    "netanyahu": ("Benjamin Netanyahu", "person"),
    "tulsi gabbard": ("Tulsi Gabbard", "person"),
    "gabbard": ("Tulsi Gabbard", "person"),
    "jim taiclet": ("Jim Taiclet", "person"),
    "taiclet": ("Jim Taiclet", "person"),
    "david petraeus": ("David Petraeus", "person"),
    "keir starmer": ("Keir Starmer", "person"),
    "starmer": ("Keir Starmer", "person"),
    "daryl caudle": ("Daryl Caudle", "person"),
    "caudle": ("Daryl Caudle", "person"),
    "su-57": ("Su-57 Felon", "product"),
    "b-1b": ("B-1B Lancer", "product"),
    "b-52": ("B-52 Stratofortress", "product"),
    "black hawk": ("UH-60 Black Hawk", "product"),
    "chinook": ("CH-47 Chinook", "product"),
    "eurofighter": ("Eurofighter Typhoon", "product"),
    "aim-260": ("AIM-260", "product"),
    "arrw": ("ARRW Hypersonic Missile", "product"),
    "sarmat": ("Sarmat ICBM", "product"),
    # --- AI / ML core concepts ---
    "artificial intelligence": ("Artificial Intelligence", "concept"),
    "ai": ("Artificial Intelligence", "concept"),
    "machine learning": ("Machine Learning", "concept"),
    "ml": ("Machine Learning", "concept"),
    "deep learning": ("Deep Learning", "concept"),
    "neural network": ("Neural Networks", "concept"),
    "neural networks": ("Neural Networks", "concept"),
    "reinforcement learning": ("Reinforcement Learning", "concept"),
    "supervised learning": ("Supervised Learning", "concept"),
    "transfer learning": ("Transfer Learning", "concept"),
    "federated learning": ("Federated Learning", "concept"),
    # --- generative AI / model families ---
    "generative ai": ("Generative AI", "concept"),
    "agentic ai": ("Agentic AI", "concept"),
    "large language model": ("Large Language Models", "concept"),
    "large language models": ("Large Language Models", "concept"),
    "llm": ("Large Language Models", "concept"),
    "foundation model": ("Foundation Models", "concept"),
    "foundation models": ("Foundation Models", "concept"),
    "diffusion model": ("Diffusion Models", "concept"),
    # --- perception / language ---
    "computer vision": ("Computer Vision", "concept"),
    "machine vision": ("Computer Vision", "concept"),
    "natural language processing": ("Natural Language Processing", "concept"),
    "nlp": ("Natural Language Processing", "concept"),
    "speech recognition": ("Speech Recognition", "concept"),
    "facial recognition": ("Facial Recognition", "concept"),
    "object detection": ("Object Detection", "concept"),
    "pattern recognition": ("Pattern Recognition", "concept"),
    "anomaly detection": ("Anomaly Detection", "concept"),
    "sensor fusion": ("Sensor Fusion", "concept"),
    # --- data / analytics ---
    "data analytics": ("Data Analytics", "concept"),
    "predictive analytics": ("Predictive Analytics", "concept"),
    "predictive maintenance": ("Predictive Maintenance", "concept"),
    "synthetic data": ("Synthetic Data", "concept"),
    # --- autonomy / robotics ---
    "autonomy": ("Autonomy", "concept"),
    "autonomous systems": ("Autonomous Systems", "concept"),
    "autonomous weapons": ("Autonomous Weapons", "concept"),
    "robotics": ("Robotics", "concept"),
    "drone swarm": ("Drone Swarm", "concept"),
    "drone swarms": ("Drone Swarm", "concept"),
    "swarm intelligence": ("Swarm Intelligence", "concept"),
    "human-machine teaming": ("Human-Machine Teaming", "concept"),
    # --- defense AI applications ---
    "isr": ("ISR", "concept"),
    "automatic target recognition": ("Automatic Target Recognition", "concept"),
    "decision support": ("Decision Support", "concept"),
    "command and control": ("Command and Control", "concept"),
    "edge computing": ("Edge Computing", "concept"),
    "digital twin": ("Digital Twin", "concept"),
    # --- domains / warfare ---
    "hypersonic": ("Hypersonic Weapons", "concept"),
    "cyber warfare": ("Cyber Warfare", "concept"),
    "electronic warfare": ("Electronic Warfare", "concept"),
    # --- defense AI programs / initiatives ---
    "replicator initiative": ("Replicator Initiative", "concept"),
    "ai arsenal": ("AI Arsenal Initiative", "concept"),
    "collaborative combat aircraft": (
        "Collaborative Combat Aircraft", "concept"
    ),
    "cca": ("Collaborative Combat Aircraft", "concept"),
    "medium unmanned surface vessel": (
        "Medium Unmanned Surface Vessel", "concept"
    ),
    "musv": ("Medium Unmanned Surface Vessel", "concept"),
    "loitering munition": ("Loitering Munitions", "concept"),
    "loitering munitions": ("Loitering Munitions", "concept"),
    "launched effect": ("Launched Effects", "concept"),
    "launched effects": ("Launched Effects", "concept"),
    "drone wingman": ("Drone Wingman", "concept"),
    "first-person-view drone": ("FPV Drone", "concept"),
    "fpv drone": ("FPV Drone", "concept"),
    "autonomous warfare": ("Autonomous Warfare", "concept"),
    "cybersecurity": ("Cybersecurity", "concept"),
    "command and control": ("Command and Control", "concept"),
    "c2": ("Command and Control", "concept"),
    "intelligence surveillance reconnaissance": ("ISR", "concept"),
    "uap": ("Unidentified Aerial Phenomena", "concept"),
    "ufo": ("Unidentified Aerial Phenomena", "concept"),
    # --- additions from May 2026 corpus sweep ---
    # AI models (Google DeepMind)
    "gemini 3.1 pro": ("Gemini 3.1 Pro", "product"),
    "gemini 3.1 flash": ("Gemini 3.1 Flash", "product"),
    "gemini 3.1 flash-lite": ("Gemini 3.1 Flash-Lite", "product"),
    "gemini 3.5 flash": ("Gemini 3.5 Flash", "product"),
    "gemini 3.5 pro": ("Gemini 3.5 Pro", "product"),
    "gemini 3 pro": ("Gemini 3 Pro", "product"),
    "gemini 3 flash": ("Gemini 3 Flash", "product"),
    "gemini 3 deep think": ("Gemini 3 Deep Think", "product"),
    "gemini robotics-er": ("Gemini Robotics-ER", "product"),
    "gemma 4": ("Gemma 4", "product"),
    "gemma scope 2": ("Gemma Scope 2", "product"),
    "lyria 3": ("Lyria 3", "product"),
    "lyria 3 pro": ("Lyria 3 Pro", "product"),
    "veo 3.1": ("Veo 3.1", "product"),
    "nano banana 2": ("Nano Banana 2", "product"),
    "nano banana pro": ("Nano Banana Pro", "product"),
    "project genie": ("Project Genie", "product"),
    "genie 3": ("Genie 3", "product"),
    "alphaevolve": ("AlphaEvolve", "product"),
    "alphaproof": ("AlphaProof", "product"),
    "alphazero": ("AlphaZero", "product"),
    "alphagenome": ("AlphaGenome", "product"),
    "alphafold": ("AlphaFold", "product"),
    "ai co-scientist": ("AI co-scientist", "product"),
    "google antigravity": ("Google Antigravity", "product"),
    # AI models (OpenAI)
    "gpt-5.5": ("GPT-5.5", "product"),
    "gpt-5.5 instant": ("GPT-5.5 Instant", "product"),
    "gpt-5.5-cyber": ("GPT-5.5-Cyber", "product"),
    "gpt-realtime-2": ("GPT-Realtime-2", "product"),
    "gpt-realtime-translate": ("GPT-Realtime-Translate", "product"),
    "codex": ("Codex", "product"),
    "stargate": ("Stargate", "concept"),
    # Benchmarks
    "arc-agi-2": ("ARC-AGI-2", "concept"),
    "lmarena": ("LMArena", "concept"),
    "gpqa diamond": ("GPQA Diamond", "concept"),
    "mmmu pro": ("MMMU Pro", "concept"),
    "facts benchmark suite": ("FACTS Benchmark Suite", "concept"),
    "finweb": ("FineWeb", "concept"),
    # Defense companies / weapons
    "castelion": ("Castelion", "organization"),
    "coaspire": ("CoAspire", "organization"),
    "leidos": ("Leidos", "organization"),
    "zone 5": ("Zone 5", "organization"),
    "perennial autonomy": ("Perennial Autonomy", "organization"),
    "quantum space": ("Quantum Space", "organization"),
    "agile space industries": ("Agile Space Industries", "organization"),
    "intelic": ("Intelic", "organization"),
    "aim defence": ("AIM Defence", "organization"),
    "sypaq systems": ("Sypaq Systems", "organization"),
    "elbit systems": ("Elbit Systems", "organization"),
    "leonardo": ("Leonardo", "organization"),
    "mbda": ("MBDA", "organization"),
    "pzl mielec": ("PZL Mielec", "organization"),
    "saildrone": ("Saildrone", "organization"),
    "symbotic": ("Symbotic", "organization"),
    "aerovironment": ("AeroVironment", "organization"),
    # Defense products
    "sarmat": ("Sarmat ICBM", "product"),
    "sarmat icbm": ("Sarmat ICBM", "product"),
    "babur cruise missile": ("Babur cruise missile", "product"),
    "brahmos": ("BrahMos", "product"),
    "agm-183a": ("AGM-183A ARRW", "product"),
    "arrw": ("AGM-183A ARRW", "product"),
    "e-7 wedgetail": ("E-7 Wedgetail", "product"),
    "e-3 sentry": ("E-3 Sentry", "product"),
    "awacs": ("AWACS", "product"),
    "blackbeard missile": ("Blackbeard missile", "product"),
    "merops": ("Merops interceptor", "product"),
    "merops interceptor": ("Merops interceptor", "product"),
    "shahed": ("Shahed", "product"),
    "gerbera": ("Gerbera", "product"),
    "michelangelo dome": ("Michelangelo Dome", "product"),
    "joint laser weapon system": ("Joint Laser Weapon System", "product"),
    "p-hel": ("Palletized High Energy Laser", "product"),
    "palletized high energy laser": ("Palletized High Energy Laser", "product"),
    "locust laser weapon system": ("LOCUST Laser Weapon System", "product"),
    "helios laser": ("HELIOS laser", "product"),
    "ifpc-hel": ("IFPC-HEL", "product"),
    "fractl": ("Fractl laser", "product"),
    "corvo strike": ("Corvo Strike", "product"),
    "f-35i adir": ("F-35I Adir", "product"),
    "ins aridhaman": ("INS Aridhaman", "product"),
    "trump class battleship": ("Trump class battleship", "product"),
    "ranger satellite": ("Ranger satellite", "product"),
    "m28 skytruck": ("M28 Skytruck", "product"),
    "antonov an-28": ("Antonov An-28", "product"),
    "eurofighter typhoon": ("Eurofighter Typhoon", "product"),
    "u-28a draco": ("U-28A Draco", "product"),
    "stryker": ("Stryker", "product"),
    "arleigh burke-class": ("Arleigh Burke-class", "product"),
    # Programs / concepts
    "golden dome": ("Golden Dome", "concept"),
    "iron dome for america": ("Iron Dome for America", "concept"),
    "operation epic fury": ("Operation Epic Fury", "concept"),
    "project flytrap": ("Project Flytrap", "concept"),
    "low-cost containerized munitions": (
        "Low-Cost Containerized Munitions", "concept"
    ),
    "lccm": ("Low-Cost Containerized Munitions", "concept"),
    "drone deals": ("Drone Deals", "concept"),
    "brave1": ("Brave1", "concept"),
    "gerasimov doctrine": ("Gerasimov Doctrine", "concept"),
    "cope cage": ("cope cages", "concept"),
    "cope cages": ("cope cages", "concept"),
    "federated learning": ("Federated Learning", "concept"),
    "model collapse": ("Model Collapse", "concept"),
    "decoupled diloco": ("Decoupled DiLoCo", "concept"),
    # US officials / commanders
    "michael guetlein": ("Michael Guetlein", "person"),
    "jim bridenstine": ("Jim Bridenstine", "person"),
    "daryl caudle": ("Daryl Caudle", "person"),
    "adm. caudle": ("Daryl Caudle", "person"),
    "hung cao": ("Hung Cao", "person"),
    "eric smith": ("Eric Smith", "person"),
    "michael conley": ("Michael Conley", "person"),
    "christopher niemi": ("Christopher Niemi", "person"),
    "frank donovan": ("Frank Donovan", "person"),
    "brad cooper": ("Brad Cooper", "person"),
    "admiral cooper": ("Brad Cooper", "person"),
    "dan driscoll": ("Dan Driscoll", "person"),
    "heath collins": ("Heath Collins", "person"),
    "tom cole": ("Tom Cole", "person"),
    # Foreign leaders / officials
    "mykhailo fedorov": ("Mykhailo Fedorov", "person"),
    "olha stefanishyna": ("Olha Stefanishyna", "person"),
    "andrii sybiha": ("Andrii Sybiha", "person"),
    "naftali bennett": ("Naftali Bennett", "person"),
    "recep tayyip erdogan": ("Recep Tayyip Erdogan", "person"),
    "ilham aliyev": ("Ilham Aliyev", "person"),
    "sergei karakayev": ("Sergei Karakayev", "person"),
    "sergei shoigu": ("Sergei Shoigu", "person"),
    # Tech leaders
    "jeff dean": ("Jeff Dean", "person"),
    "demis hassabis": ("Demis Hassabis", "person"),
    "john jumper": ("John Jumper", "person"),
    # MIT/academic
    "jacob andreas": ("Jacob Andreas", "person"),
    "daron acemoglu": ("Daron Acemoglu", "person"),
    "gabriele farina": ("Gabriele Farina", "person"),
    "leo anthony celi": ("Leo Anthony Celi", "person"),
    # Organizations - AI / research / corporate
    "google deepmind": ("Google DeepMind", "organization"),
    "openai": ("OpenAI", "organization"),
    "anthropic": ("Anthropic", "organization"),
    "mit-ibm computing research lab": (
        "MIT-IBM Computing Research Lab", "organization"
    ),
    "mit-ibm watson ai lab": ("MIT-IBM Watson AI Lab", "organization"),
    "openprotein.ai": ("OpenProtein.AI", "organization"),
    "isomorphic labs": ("Isomorphic Labs", "organization"),
    "uk ai security institute": ("UK AI Security Institute", "organization"),
    "aisi": ("UK AI Security Institute", "organization"),
    "liquid ai": ("Liquid AI", "organization"),
    "humain": ("HUMAIN", "organization"),
    "kaust": ("KAUST", "organization"),
    "seoul national university": ("Seoul National University", "organization"),
    "kaist": ("KAIST", "organization"),
    "hasso plattner institute": ("Hasso Plattner Institute", "organization"),
    "beacon biosignals": ("Beacon Biosignals", "organization"),
    "tanstack": ("TanStack", "organization"),
    "uber": ("Uber", "organization"),
    "pwc": ("PwC", "organization"),
    "accenture": ("Accenture", "organization"),
    "deloitte": ("Deloitte", "organization"),
    "mckinsey": ("McKinsey", "organization"),
    "bain & company": ("Bain & Company", "organization"),
    "bcg": ("Boston Consulting Group", "organization"),
    "boston consulting group": ("Boston Consulting Group", "organization"),
    "klarna": ("Klarna", "organization"),
    "amd": ("AMD", "organization"),
    "broadcom": ("Broadcom", "organization"),
    "sea limited": ("Sea Limited", "organization"),
    "shopee": ("Shopee", "organization"),
    "autoscout24": ("AutoScout24", "organization"),
    "parloa": ("Parloa", "organization"),
    "tomoro": ("Tomoro", "organization"),
    "openai deployment company": (
        "OpenAI Deployment Company", "organization"
    ),
    # Government agencies
    "missile defense agency": ("Missile Defense Agency", "organization"),
    "mda": ("Missile Defense Agency", "organization"),
    "irgc navy": ("IRGC Navy", "organization"),
    "department of war": ("Department of War", "organization"),
    "defense innovation unit": ("Defense Innovation Unit", "organization"),
    "ussocom": ("U.S. Special Operations Command", "organization"),
    "southcom": ("U.S. Southern Command", "organization"),
    # Places
    "strait of hormuz": ("Strait of Hormuz", "place"),
    "plesetsk cosmodrome": ("Plesetsk Cosmodrome", "place"),
    "tulsa": ("Tulsa", "place"),
    "lithuania": ("Lithuania", "place"),
    "latvia": ("Latvia", "place"),
    "republic of korea": ("South Korea", "place"),
    "lebanon": ("Lebanon", "place"),
    # Academic conferences
    "iclr": ("ICLR", "organization"),
    "neurips": ("NeurIPS", "organization"),
    "iccv": ("ICCV", "organization"),
    "aaai": ("AAAI", "organization"),
    "emnlp": ("EMNLP", "organization"),
    "corl": ("CoRL", "organization"),
    "acl": ("ACL", "organization"),
}


# AI capability taxonomy. Groups the `concept` entities into the subfields an
# AI / defense reader thinks in — LLMs, RL, perception, autonomy, ISR/C2,
# cyber/EW, directed-energy/hypersonics, and the named defense programs that
# tie those capabilities to deployment. Each subfield is a curated list of
# canonical names that appear (or could appear) in GAZETTEER as concept-type
# entries. `concepts_for_subfield()` resolves these to live graph nodes by
# canonical-name match; new capabilities added to GAZETTEER are picked up
# automatically once they're listed below.
#
# Kept hand-curated rather than auto-derived so a curator stays in control of
# how subfields are presented to a learner — the whole purpose of the
# Capabilities view is editorial scaffolding for the AI expert who wants a
# map of their territory, not yet another auto-generated cluster.
SUBFIELDS = (
    {
        "id": "foundation_models",
        "label": "Foundation models & LLMs",
        "tagline": "Large generative models — text, image, multimodal.",
        "concepts": (
            "Large Language Models", "Foundation Models", "Generative AI",
            "Agentic AI", "Diffusion Models", "Model Collapse",
        ),
    },
    {
        "id": "machine_learning",
        "label": "Machine learning & reinforcement learning",
        "tagline": "The training-and-optimization core under everything else.",
        "concepts": (
            "Machine Learning", "Deep Learning", "Neural Networks",
            "Reinforcement Learning", "Supervised Learning",
            "Transfer Learning", "Federated Learning",
        ),
    },
    {
        "id": "perception",
        "label": "Perception — vision, speech, NLP",
        "tagline": "Turning sensor and language data into structured signals.",
        "concepts": (
            "Computer Vision", "Natural Language Processing",
            "Speech Recognition", "Facial Recognition", "Object Detection",
            "Pattern Recognition", "Anomaly Detection", "Sensor Fusion",
        ),
    },
    {
        "id": "autonomy",
        "label": "Autonomy & robotics",
        "tagline": "Self-directed systems on the ground, in the air, at sea.",
        "concepts": (
            "Autonomy", "Autonomous Systems", "Autonomous Weapons",
            "Robotics", "Drone Swarm", "Swarm Intelligence",
            "Human-Machine Teaming", "Autonomous Warfare",
        ),
    },
    {
        "id": "isr_c2",
        "label": "ISR & command-and-control",
        "tagline": "Sensing, fusing, deciding — the defense AI core loop.",
        "concepts": (
            "ISR", "Automatic Target Recognition", "Decision Support",
            "Command and Control", "Edge Computing", "Digital Twin",
            "Predictive Analytics", "Predictive Maintenance",
            "Data Analytics", "Synthetic Data",
        ),
    },
    {
        "id": "cyber_ew",
        "label": "Cyber & electronic warfare",
        "tagline": "Defending and attacking through code and the spectrum.",
        "concepts": (
            "Cyber Warfare", "Electronic Warfare", "Cybersecurity",
        ),
    },
    {
        "id": "directed_energy",
        "label": "Directed energy & hypersonics",
        "tagline": "Lasers, microwaves, and Mach-5+ kinetics.",
        "concepts": (
            "Hypersonic Weapons",
        ),
    },
    {
        "id": "defense_programs",
        "label": "Defense AI programs",
        "tagline": "The named initiatives wiring AI into U.S. doctrine.",
        "concepts": (
            "Replicator Initiative", "AI Arsenal Initiative",
            "Collaborative Combat Aircraft",
            "Medium Unmanned Surface Vessel", "Loitering Munitions",
            "Launched Effects", "Drone Wingman", "FPV Drone",
        ),
    },
)


def subfield_for_concept(canonical_name):
    """Return the subfield id a concept belongs to, or None.

    Lets the frontend tag a concept node with its subfield without a second
    lookup. A concept that isn't in any subfield list is treated as
    uncategorized — present in the graph, just not on the Capabilities map.
    """
    target = (canonical_name or "").strip()
    for subfield in SUBFIELDS:
        if target in subfield["concepts"]:
            return subfield["id"]
    return None
