"""Curated national-security gazetteer for high-precision entity matching.

Maps a lowercase surface form to a (canonical name, entity type) pair.
Entity types: place, organization, person, group, product, concept.
"""

GAZETTEER = {
    # --- countries / places ---
    "united states": ("United States", "place"),
    "u.s.": ("United States", "place"),
    "america": ("United States", "place"),
    "china": ("China", "place"),
    "russia": ("Russia", "place"),
    "ukraine": ("Ukraine", "place"),
    "iran": ("Iran", "place"),
    "north korea": ("North Korea", "place"),
    "south korea": ("South Korea", "place"),
    "israel": ("Israel", "place"),
    "taiwan": ("Taiwan", "place"),
    "india": ("India", "place"),
    "japan": ("Japan", "place"),
    "united kingdom": ("United Kingdom", "place"),
    "u.k.": ("United Kingdom", "place"),
    "germany": ("Germany", "place"),
    "france": ("France", "place"),
    "australia": ("Australia", "place"),
    "pacific": ("Pacific", "place"),
    "indo-pacific": ("Indo-Pacific", "place"),
    "middle east": ("Middle East", "place"),
    "europe": ("Europe", "place"),
    "poland": ("Poland", "place"),
    "sweden": ("Sweden", "place"),
    "finland": ("Finland", "place"),
    "norway": ("Norway", "place"),
    "denmark": ("Denmark", "place"),
    "netherlands": ("Netherlands", "place"),
    "belgium": ("Belgium", "place"),
    "italy": ("Italy", "place"),
    "spain": ("Spain", "place"),
    "greece": ("Greece", "place"),
    "turkey": ("Turkey", "place"),
    "romania": ("Romania", "place"),
    "canada": ("Canada", "place"),
    "mexico": ("Mexico", "place"),
    "cuba": ("Cuba", "place"),
    "venezuela": ("Venezuela", "place"),
    "egypt": ("Egypt", "place"),
    "saudi arabia": ("Saudi Arabia", "place"),
    "united arab emirates": ("United Arab Emirates", "place"),
    "qatar": ("Qatar", "place"),
    "iraq": ("Iraq", "place"),
    "syria": ("Syria", "place"),
    "yemen": ("Yemen", "place"),
    "afghanistan": ("Afghanistan", "place"),
    "pakistan": ("Pakistan", "place"),
    "vietnam": ("Vietnam", "place"),
    "philippines": ("Philippines", "place"),
    "singapore": ("Singapore", "place"),
    "argentina": ("Argentina", "place"),
    "strait of hormuz": ("Strait of Hormuz", "place"),
    # --- organizations / agencies ---
    "pentagon": ("Pentagon", "organization"),
    "department of defense": ("Department of Defense", "organization"),
    "dod": ("Department of Defense", "organization"),
    "u.s. military": ("U.S. Military", "organization"),
    "white house": ("White House", "organization"),
    "congress": ("Congress", "organization"),
    "navy": ("U.S. Navy", "organization"),
    "u.s. navy": ("U.S. Navy", "organization"),
    "army": ("U.S. Army", "organization"),
    "u.s. army": ("U.S. Army", "organization"),
    "air force": ("U.S. Air Force", "organization"),
    "space force": ("U.S. Space Force", "organization"),
    "marine corps": ("U.S. Marine Corps", "organization"),
    "cia": ("Central Intelligence Agency", "organization"),
    "nsa": ("National Security Agency", "organization"),
    "fbi": ("Federal Bureau of Investigation", "organization"),
    "darpa": ("DARPA", "organization"),
    "nato": ("NATO", "organization"),
    "united nations": ("United Nations", "organization"),
    "european union": ("European Union", "organization"),
    "pla": ("People's Liberation Army", "organization"),
    "people's liberation army": ("People's Liberation Army", "organization"),
    "socom": ("U.S. Special Operations Command", "organization"),
    "centcom": ("U.S. Central Command", "organization"),
    "southcom": ("U.S. Southern Command", "organization"),
    "coast guard": ("U.S. Coast Guard", "organization"),
    "national guard": ("National Guard", "organization"),
    "irgc": ("Islamic Revolutionary Guard Corps", "organization"),
    # --- defense industry ---
    "lockheed martin": ("Lockheed Martin", "organization"),
    "boeing": ("Boeing", "organization"),
    "raytheon": ("Raytheon", "organization"),
    "rtx": ("RTX", "organization"),
    "northrop grumman": ("Northrop Grumman", "organization"),
    "general dynamics": ("General Dynamics", "organization"),
    "bae systems": ("BAE Systems", "organization"),
    "l3harris": ("L3Harris", "organization"),
    "anduril": ("Anduril", "organization"),
    "palantir": ("Palantir", "organization"),
    "spacex": ("SpaceX", "organization"),
    "openai": ("OpenAI", "organization"),
    "shield ai": ("Shield AI", "organization"),
    # --- products / systems ---
    "f-35": ("F-35", "product"),
    "f-16": ("F-16", "product"),
    "b-21": ("B-21 Raider", "product"),
    "patriot": ("Patriot missile system", "product"),
    "tomahawk": ("Tomahawk missile", "product"),
    "himars": ("HIMARS", "product"),
    "reaper": ("MQ-9 Reaper", "product"),
    "mq-9": ("MQ-9 Reaper", "product"),
    "global hawk": ("Global Hawk", "product"),
    "su-57": ("Su-57 Felon", "product"),
    "b-1b": ("B-1B Lancer", "product"),
    "b-52": ("B-52 Stratofortress", "product"),
    "black hawk": ("UH-60 Black Hawk", "product"),
    "chinook": ("CH-47 Chinook", "product"),
    "eurofighter": ("Eurofighter Typhoon", "product"),
    "aim-260": ("AIM-260", "product"),
    "arrw": ("ARRW Hypersonic Missile", "product"),
    "sarmat": ("Sarmat ICBM", "product"),
    # --- AI / concepts ---
    "artificial intelligence": ("Artificial Intelligence", "concept"),
    "ai": ("Artificial Intelligence", "concept"),
    "machine learning": ("Machine Learning", "concept"),
    "autonomous weapons": ("Autonomous Weapons", "concept"),
    "drone swarm": ("Drone Swarm", "concept"),
    "hypersonic": ("Hypersonic Weapons", "concept"),
    "cyber warfare": ("Cyber Warfare", "concept"),
    "electronic warfare": ("Electronic Warfare", "concept"),
}
